/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.co.s13.syntaxtextareafx.langs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import in.co.s13.syntaxtextareafx.meta.Language;
import java.util.Collections;

/**
 * Comment-only highlighting for Automake (source); no keyword or string rules.
 *
 * <p>Hand-written, not generated by {@code Generator}. See that class's
 * Javadoc for the JSON-generated approach used for most other languages
 * in this package.
 */
public class Automake implements Language {


    @Override
    public Pattern generatePattern() {
        Pattern pattern;
String COMMENT_PATTERN;
COMMENT_PATTERN = "#[^\n]*" ;//+ "|" + "/\\*[\\s\\S]*?\\*/";


        pattern = Pattern.compile(
          "(?<COMMENT>" + COMMENT_PATTERN + ")"
        );
        return pattern;
    }

    @Override
    public String getStyleClass(Matcher matcher) {
        return matcher.group("COMMENT") != null ? "comment"
                : null;
    }

    @Override
    public ArrayList<String> getKeywords() {
        ArrayList<String> keywordList = new ArrayList<>();
        Collections.sort(keywordList);
        return keywordList;
    }

}
