/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.co.s13.syntaxtextareafx.langs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import in.co.s13.syntaxtextareafx.meta.Language;
import java.util.Collections;

/**
 * Keyword, string and comment highlighting for OpenGL Shading Language (source).
 *
 * <p>Generated by {@code Generator} from gtksourceview's glsl.json
 * language definition.
 */
public class Glsl implements Language {

    String PREPROCESSOR[] = new String[]{"define", "undef", "(if|elif)([ \\t]+defined)?", "ifdef", "ifndef", "else", "endif", "error", "pragma", "extension", "version", "line"};
    String COMMON_MACROS[] = new String[]{"__VERSION__", "__LINE__", "__FILE__"};
    String KEYWORDS[] = new String[]{"break", "continue", "discard", "do", "for", "if", "else", "return", "while", "switch", "case", "default", "attribute", "const", "in", "inout", "out", "uniform", "varying", "invariant", "centroid", "flat", "smooth", "noperspective", "layout", "patch", "sample", "subroutine", "lowp", "mediump", "highp", "precision"};
    String PRIMITIVES[] = new String[]{"bool", "float", "double", "int", "uint", "struct", "void", "[bdiu]?vec[2-4]", "[d]?mat[2-4]", "[d]?mat[2-4]x[2-4]", "[iu]?sampler[1-3]D", "sampler[1-2]DShadow", "[iu]?sampler[1-2]DArray", "sampler[1-2]DArrayShadow", "[iu]?samplerCube", "samplerCubeShadow", "[iu]?sampler2DRect", "sampler2DRectShadow", "[iu]?samplerBuffer", "[iu]?sampler2DMS", "[iu]?sampler2DMSArray", "[iu]?sampler2DMSCubeArray", "samplerCubeArrayShadow"};
    String RESERVED_KEYWORDS_FOR_FUTURE_USE[] = new String[]{"common", "partition", "active", "asm", "class", "union", "enum", "typedef", "template", "this", "packed", "goto", "inline", "noinline", "volatile", "public", "static", "extern", "external", "interface", "long", "short", "half", "fixed", "unsigned", "input", "output", "[hf]vec[2-4]", "sampler3DRect", "filter", "sizeof", "cast", "namespace", "using", "row_major"};
    String BUILTIN_FUNCTIONS[] = new String[]{"radians", "degrees", "sin", "cos", "tan", "asin", "acos", "atan", "sinh", "cosh", "tanh", "asinh", "acosh", "atanh", "pow", "exp", "log", "exp2", "log2", "sqrt", "inversesqrt", "abs", "sign", "floor", "trunc", "round", "roundEven", "ceil", "fract", "mod", "modf", "min", "max", "clamp", "mix", "step", "smoothstep", "isnan", "isinf", "floatBitsToInt", "floatBitsToUint", "intBitsToFloat", "uintBitsToFloat", "fma", "frexp", "ldexp", "packUnorm2x16", "packUnorm4x8", "packSnorm4x8", "unpackUnorm2x16", "unpackUnorm4x8", "unpackSnorm4x8", "packDouble2x32", "unpackDouble2x32", "length", "distance", "dot", "cross", "normalize", "ftransform", "faceforward", "reflect", "refract", "matrixCompMult", "outerProduct", "transpose", "determinant", "inverse", "lessThan", "lessThanEqual", "greaterThan", "greaterThanEqual", "equal", "notEqual", "any", "all", "not", "uaddCarry", "usubBorrow", "umulExtended", "imulExtended", "bitfieldExtract", "bitfildInsert", "bitfieldReverse", "bitCount", "findLSB", "findMSB", "textureSize", "textureQueryLOD", "texture", "textureProj", "textureLod", "textureOffset", "texelFetch", "texelFetchOffset", "textureProjOffset", "textureLodOffset", "textureProjLod", "textureProjLodOffset", "textureGrad", "textureGradOffset", "textureProjGrad", "textureProjGradOffset", "textureGather", "textureGatherOffset", "texture[1-3]D", "texture[1-3]DProj", "texture[1-3]DLod", "texture[1-3]DProjLod", "textureCube", "textureCubeLod", "shadow[1-2]D", "shadow[1-2]DProj", "shadow[1-2]DLod", "shadow[1-2]DProjLod", "dFdx", "dFdy", "fwidth", "interpolateAtCentroid", "interpolateAtSample", "interpolateAtOffset", "noise[1-4]", "EmitStreamVertex", "EndStreamPrimitive", "EmitVertex", "EndPrimitive", "barrier"};
    String BUILTIN_VARIABLES[] = new String[]{"gl_VertexID", "gl_InstanceID", "gl_Position", "gl_PointSize", "gl_ClipDistance", "gl_PrimitiveIDIn", "gl_InvocationID", "gl_PrimitiveID", "gl_Layer", "gl_PatchVerticesIn", "gl_TessLevelOuter", "gl_TessLevelInner", "gl_TessCoord", "gl_FragCoord", "gl_FrontFacing", "gl_PointCoord", "gl_SampleID", "gl_SamplePosition", "gl_FragColor", "gl_FragData", "gl_FragDepth", "gl_SampleMask", "gl_ClipVertex", "gl_FrontColor", "gl_BackColor", "gl_FrontSecondaryColor", "gl_BackSecondaryColor", "gl_TexCoord", "gl_FogFragCoord", "gl_Color", "gl_SecondaryColor", "gl_Normal", "gl_Vertex", "gl_MultiTexCoord[0-7]", "gl_FogCoord"};
    String BUILTIN_CONSTANTS[] = new String[]{"gl_MaxVertexAttribs", "gl_MaxVertexUniformComponents", "gl_MaxVaryingFloats", "gl_MaxVaryingComponents", "gl_MaxVertexOutputComponents", "gl_MaxGeometryInputComponents", "gl_MaxGeometryOutputComponents", "gl_MaxFragmentInputComponents", "gl_MaxVertexTextureImageUnits", "gl_MaxCombinedTextureImageUnits", "gl_MaxTextureImageUnits", "gl_MaxFragmentUniformComponents", "gl_MaxDrawBuffers", "gl_MaxClipDistances", "gl_MaxGeometryTextureImageUnits", "gl_MaxGeometryOutputVertices", "gl_MaxGeometryTotalOutputComponents", "gl_MaxGeometryUniformComponents", "gl_MaxGeometryVaryingComponents", "gl_MaxTessControlInputComponents", "gl_MaxTessControlOutputComponents", "gl_MaxTessControlTextureImageUnits", "gl_MaxTessControlUniformComponents", "gl_MaxTessControlTotalOutputComponents", "gl_MaxTessEvaluationInputComponents", "gl_MaxTessEvaluationOutputComponents", "gl_MaxTessEvaluationTextureImageUnits", "gl_MaxTessEvaluationUniformComponents", "gl_MaxTessPatchComponents", "gl_MaxPatchVertices", "gl_MaxTessGenLevel", "gl_MaxTextureUnits", "gl_MaxTextureCoords", "gl_MaxClipPlanes"};
    String BUILTIN_UNIFORM_STATES[] = new String[]{"gl_DepthRange", "gl_ModelViewMatrix", "gl_ProjectionMatrix", "gl_ModelViewProjectionMatrix", "gl_TextureMatrix", "gl_NormalMatrix", "gl_ModelViewMatrixInverse", "gl_ProjectionMatrixInverse", "gl_ModelViewProjectionMatrixInverse", "gl_TextureMatrixInverse", "gl_ModelViewMatrixTranspose", "gl_ProjectionMatrixTranspose", "gl_ModelViewProjectionMatrixTranspose", "gl_TextureMatrixTranspose", "gl_ModelViewMatrixInverseTranspose", "gl_ProjectionMatrixInverseTranspose", "gl_ModelViewProjectionMatrixInverseTranspose", "gl_TextureMatrixInverseTranspose", "gl_NormalScale", "gl_ClipPlane", "gl_Point", "gl_FrontMaterial", "gl_BackMaterial", "gl_LightSource", "gl_LightModel", "gl_FrontLightModelProduct", "gl_BackLightModelProduct", "gl_FrontLightProduct", "gl_BackLightProduct", "gl_TextureEnvColor", "gl_EyePlaneS", "gl_EyePlaneT", "gl_EyePlaneR", "gl_EyePlaneQ", "gl_ObjectPlaneS", "gl_ObjectPlaneT", "gl_ObjectPlaneR", "gl_ObjectPlaneQ", "gl_Fog"};

    @Override
    public Pattern generatePattern() {
        String STRING_PATTERN = "\"[^\"\\\\]*+(?:\\\\.[^\"\\\\]*+)*+\"|'[^'\\\\]*+(?:\\\\.[^'\\\\]*+)*+'";
        String COMMENT_PATTERN = "\\Q//\\E[^\\n]*|\\Q/*\\E[\\s\\S]*?\\Q*/\\E";
        String PREPROCESSOR_PATTERN = "\\b(" + String.join("|", PREPROCESSOR) + ")\\b";
        String COMMON_MACROS_PATTERN = "\\b(" + String.join("|", COMMON_MACROS) + ")\\b";
        String KEYWORDS_PATTERN = "\\b(" + String.join("|", KEYWORDS) + ")\\b";
        String PRIMITIVES_PATTERN = "\\b(" + String.join("|", PRIMITIVES) + ")\\b";
        String RESERVED_KEYWORDS_FOR_FUTURE_USE_PATTERN = "\\b(" + String.join("|", RESERVED_KEYWORDS_FOR_FUTURE_USE) + ")\\b";
        String BUILTIN_FUNCTIONS_PATTERN = "\\b(" + String.join("|", BUILTIN_FUNCTIONS) + ")\\b";
        String BUILTIN_VARIABLES_PATTERN = "\\b(" + String.join("|", BUILTIN_VARIABLES) + ")\\b";
        String BUILTIN_CONSTANTS_PATTERN = "\\b(" + String.join("|", BUILTIN_CONSTANTS) + ")\\b";
        String BUILTIN_UNIFORM_STATES_PATTERN = "\\b(" + String.join("|", BUILTIN_UNIFORM_STATES) + ")\\b";

        Pattern pattern = Pattern.compile(
                "(?<STRING>" + STRING_PATTERN + ")"
                + "|(?<COMMENT>" + COMMENT_PATTERN + ")"
                + "|(?<PREPROCESSOR>" + PREPROCESSOR_PATTERN + ")"
                + "|(?<COMMONMACROS>" + COMMON_MACROS_PATTERN + ")"
                + "|(?<KEYWORDS>" + KEYWORDS_PATTERN + ")"
                + "|(?<PRIMITIVES>" + PRIMITIVES_PATTERN + ")"
                + "|(?<RESERVEDKEYWORDSFORFUTUREUSE>" + RESERVED_KEYWORDS_FOR_FUTURE_USE_PATTERN + ")"
                + "|(?<BUILTINFUNCTIONS>" + BUILTIN_FUNCTIONS_PATTERN + ")"
                + "|(?<BUILTINVARIABLES>" + BUILTIN_VARIABLES_PATTERN + ")"
                + "|(?<BUILTINCONSTANTS>" + BUILTIN_CONSTANTS_PATTERN + ")"
                + "|(?<BUILTINUNIFORMSTATES>" + BUILTIN_UNIFORM_STATES_PATTERN + ")"
        );
        return pattern;
    }

    @Override
    public String getStyleClass(Matcher matcher) {
        return matcher.group("STRING") != null ? "string"
                : matcher.group("COMMENT") != null ? "comment"
                : matcher.group("PREPROCESSOR") != null ? "preprocessor"
                : matcher.group("COMMONMACROS") != null ? "common-macros"
                : matcher.group("KEYWORDS") != null ? "keywords"
                : matcher.group("PRIMITIVES") != null ? "primitives"
                : matcher.group("RESERVEDKEYWORDSFORFUTUREUSE") != null ? "reserved-keywords-for-future-use"
                : matcher.group("BUILTINFUNCTIONS") != null ? "builtin-functions"
                : matcher.group("BUILTINVARIABLES") != null ? "builtin-variables"
                : matcher.group("BUILTINCONSTANTS") != null ? "builtin-constants"
                : matcher.group("BUILTINUNIFORMSTATES") != null ? "builtin-uniform-states"
                : null;
    }

    @Override
    public ArrayList<String> getKeywords() {
        ArrayList<String> keywordList = new ArrayList<>();
        keywordList.addAll(Arrays.asList(PREPROCESSOR));
        keywordList.addAll(Arrays.asList(COMMON_MACROS));
        keywordList.addAll(Arrays.asList(KEYWORDS));
        keywordList.addAll(Arrays.asList(PRIMITIVES));
        keywordList.addAll(Arrays.asList(RESERVED_KEYWORDS_FOR_FUTURE_USE));
        keywordList.addAll(Arrays.asList(BUILTIN_FUNCTIONS));
        keywordList.addAll(Arrays.asList(BUILTIN_VARIABLES));
        keywordList.addAll(Arrays.asList(BUILTIN_CONSTANTS));
        keywordList.addAll(Arrays.asList(BUILTIN_UNIFORM_STATES));
        Collections.sort(keywordList);
        return keywordList;
    }

}
