/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.co.s13.syntaxtextareafx.langs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import in.co.s13.syntaxtextareafx.meta.Language;
import java.util.Collections;

/**
 * Keyword, string and comment highlighting for IDL (source).
 *
 * <p>Generated by {@code Generator} from gtksourceview's idl.json
 * language definition.
 */
public class Idl implements Language {

    String KEYWORDS[] = new String[]{"abstract", "attribute", "case", "const", "context", "custom", "default", "exception", "enum", "factory", "false", "in", "inout", "interface", "local", "module", "native", "oneway", "out", "private", "public", "raises", "readonly", "struct", "support", "switch", "true", "truncatable", "typedef", "union", "valuetype"};
    String TYPES[] = new String[]{"any", "boolean", "char", "double", "fixed", "float", "long", "Object", "octet", "sequence", "short", "string", "unsigned", "ValueBase", "void", "wchar", "wstring"};
    String PREPROCESSOR_DEFINITIONS[] = new String[]{"if", "ifdef", "ifndef", "else", "elif", "define", "endif", "undef"};

    @Override
    public Pattern generatePattern() {
        String STRING_PATTERN = "\"[^\"\\\\]*+(?:\\\\.[^\"\\\\]*+)*+\"|'[^'\\\\]*+(?:\\\\.[^'\\\\]*+)*+'";
        String COMMENT_PATTERN = "\\Q//\\E[^\\n]*";
        String KEYWORDS_PATTERN = "\\b(" + String.join("|", KEYWORDS) + ")\\b";
        String TYPES_PATTERN = "\\b(" + String.join("|", TYPES) + ")\\b";
        String PREPROCESSOR_DEFINITIONS_PATTERN = "\\b(" + String.join("|", PREPROCESSOR_DEFINITIONS) + ")\\b";

        Pattern pattern = Pattern.compile(
                "(?<STRING>" + STRING_PATTERN + ")"
                + "|(?<COMMENT>" + COMMENT_PATTERN + ")"
                + "|(?<KEYWORDS>" + KEYWORDS_PATTERN + ")"
                + "|(?<TYPES>" + TYPES_PATTERN + ")"
                + "|(?<PREPROCESSORDEFINITIONS>" + PREPROCESSOR_DEFINITIONS_PATTERN + ")"
        );
        return pattern;
    }

    @Override
    public String getStyleClass(Matcher matcher) {
        return matcher.group("STRING") != null ? "string"
                : matcher.group("COMMENT") != null ? "comment"
                : matcher.group("KEYWORDS") != null ? "keywords"
                : matcher.group("TYPES") != null ? "types"
                : matcher.group("PREPROCESSORDEFINITIONS") != null ? "preprocessor-definitions"
                : null;
    }

    @Override
    public ArrayList<String> getKeywords() {
        ArrayList<String> keywordList = new ArrayList<>();
        keywordList.addAll(Arrays.asList(KEYWORDS));
        keywordList.addAll(Arrays.asList(TYPES));
        keywordList.addAll(Arrays.asList(PREPROCESSOR_DEFINITIONS));
        Collections.sort(keywordList);
        return keywordList;
    }

}
