/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.co.s13.syntaxtextareafx.langs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import in.co.s13.syntaxtextareafx.meta.Language;
import java.util.Collections;

/**
 * Keyword, string and comment highlighting for Tcl (script).
 *
 * <p>Generated by {@code Generator} from gtksourceview's tcl.json
 * language definition.
 */
public class Tcl implements Language {

    String KEYWORD[] = new String[]{"string", "subst", "regexp", "regsub", "scan", "format", "binary", "list", "split", "join", "concat", "llength", "lrange", "lsearch", "lreplace", "lindex", "lsort", "linsert", "lrepeat", "dict", "if", "else", "elseif", "then", "for", "foreach", "switch", "case", "while", "continue", "return", "break", "catch", "error", "eval", "uplevel", "after", "update", "vwait", "proc", "rename", "set", "lset", "lassign", "unset", "namespace", "variable", "upvar", "global", "trace", "array", "incr", "append", "lappend", "expr", "file", "open", "close", "socket", "fconfigure", "puts", "gets", "read", "seek", "tell", "eof", "flush", "fblocked", "fcopy", "fileevent", "source", "load", "unload", "package", "info", "interp", "history", "bgerror", "unknown", "memory", "cd", "pwd", "clock", "time", "exec", "glob", "pid", "exit"};

    @Override
    public Pattern generatePattern() {
        String STRING_PATTERN = "\"[^\"\\\\]*+(?:\\\\.[^\"\\\\]*+)*+\"|'[^'\\\\]*+(?:\\\\.[^'\\\\]*+)*+'";
        String COMMENT_PATTERN = "\\Q#\\E[^\\n]*";
        String KEYWORD_PATTERN = "\\b(" + String.join("|", KEYWORD) + ")\\b";

        Pattern pattern = Pattern.compile(
                "(?<STRING>" + STRING_PATTERN + ")"
                + "|(?<COMMENT>" + COMMENT_PATTERN + ")"
                + "|(?<KEYWORD>" + KEYWORD_PATTERN + ")"
        );
        return pattern;
    }

    @Override
    public String getStyleClass(Matcher matcher) {
        return matcher.group("STRING") != null ? "string"
                : matcher.group("COMMENT") != null ? "comment"
                : matcher.group("KEYWORD") != null ? "keyword"
                : null;
    }

    @Override
    public ArrayList<String> getKeywords() {
        ArrayList<String> keywordList = new ArrayList<>();
        keywordList.addAll(Arrays.asList(KEYWORD));
        Collections.sort(keywordList);
        return keywordList;
    }

}
