/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.co.s13.syntaxtextareafx.langs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import in.co.s13.syntaxtextareafx.meta.Language;
import java.util.Collections;

/**
 * Keyword, string and comment highlighting for Yacc (other).
 *
 * <p>Generated by {@code Generator} from gtksourceview's yacc.json
 * language definition.
 */
public class Yacc implements Language {

    String OPTIONS[] = new String[]{"debug", "defines", "destructor", "dprec", "error-verbose", "expect", "glr-parser", "initial-action", "left", "lex-param", "locations", "merge", "name-prefix", "no[_-]lines", "nonassoc", "output", "parse-param", "prec", "pure[_-]parser", "raw", "require", "right", "start", "token[_-]table", "union"};

    @Override
    public Pattern generatePattern() {
        String STRING_PATTERN = "\"[^\"\\\\]*+(?:\\\\.[^\"\\\\]*+)*+\"|'[^'\\\\]*+(?:\\\\.[^'\\\\]*+)*+'";
        String COMMENT_PATTERN = "\\Q//\\E[^\\n]*|\\Q/*\\E[\\s\\S]*?\\Q*/\\E";
        String OPTIONS_PATTERN = "\\b(" + String.join("|", OPTIONS) + ")\\b";

        Pattern pattern = Pattern.compile(
                "(?<STRING>" + STRING_PATTERN + ")"
                + "|(?<COMMENT>" + COMMENT_PATTERN + ")"
                + "|(?<OPTIONS>" + OPTIONS_PATTERN + ")"
        );
        return pattern;
    }

    @Override
    public String getStyleClass(Matcher matcher) {
        return matcher.group("STRING") != null ? "string"
                : matcher.group("COMMENT") != null ? "comment"
                : matcher.group("OPTIONS") != null ? "options"
                : null;
    }

    @Override
    public ArrayList<String> getKeywords() {
        ArrayList<String> keywordList = new ArrayList<>();
        keywordList.addAll(Arrays.asList(OPTIONS));
        Collections.sort(keywordList);
        return keywordList;
    }

}
